use_frameworks!

platform :ios, '8.0'

target 'XYXLLogining_Example' do
  pod 'XYXLLogining', :path => '../'

  target 'XYXLLogining_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
